packages:
  - examples/*
  - packages/*
  - tools/*

catalog:
  "@types/node": ^24.13.1
  typescript: ^5.9.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  "@vitest/coverage-v8": latest
  "@vitest/ui": latest

  magic-string: ^0.30.21
  "@formatjs/icu-messageformat-parser": ^3.5.11
  "@oxc-project/types": latest
  "oxc-parser": latest

  knip: latest
  "@changesets/cli": latest

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

minimumReleaseAge: 720
